/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Movie list Data
 */
export const MOVIE_LIST_DATA = [
  {
    'sort': 0,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_first'),
    'title': '八角笼中',
    'describe': '讲述冰上女运动员之间团结友爱，互帮互助的故事',
    'movieImage': $r('app.media.ic_movie_one'),
    'cardImage': '/common/ic_movie_one.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。',
    'weburl': 'https://www.maoyan.com/cinemas?movieId=1413252&merCode=1000315'
  },
  {
    'sort': 1,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_second'),
    'title': '茶啊二中',
    'describe': '通过地道战的方式与日寇作斗争的故事',
    'movieImage': $r('app.media.ic_movie_two'),
    'cardImage': '/common/ic_movie_two.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。',
    'weburl':'https://www.maoyan.com/films/1431907'
  },
  {
    'sort': 2,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_third'),
    'title': '我爱你！',
    'describe': '带领群众继续作斗争，最后壮烈牺牲的故事',
    'movieImage': $r('app.media.ic_movie_three'),
    'cardImage': '/common/ic_movie_three.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。',
    'weburl':'https://www.maoyan.com/films/1470379'
  },
  {
    'sort': 3,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_fourth'),
    'title': '长安三万里',
    'describe': '抗日战争时期，八路军剿灭日本特务的故事',
    'movieImage': $r('app.media.ic_movie_four'),
    'cardImage': '/common/ic_movie_four.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_empty_star')],
    'rating': '9.0',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。',
    'weburl':'https://www.maoyan.com/films/1475137'
  },
  {
    'sort': 4,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_fifth'),
    'title': '消失的她',
    'describe': '花木兰替父从军，英姿飒爽的故事',
    'movieImage': $r('app.media.ic_movie_five'),
    'cardImage': '/common/ic_movie_five.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_empty_star')],
    'rating': '9.0',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。',
    'weburl':'https://www.maoyan.com/films/1452790'
  },
  {
    'sort': 5,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '蜘蛛侠：纵横宇宙',
    'describe': '讲述了一对相爱的年轻人，受到昏君的迫害，遇到仙人相助的故事',
    'movieImage': $r('app.media.ic_movie_six'),
    'cardImage': '/common/ic_movie_six.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。',
    'weburl':'https://www.maoyan.com/films/1298450'
  },
  {
    'sort': 6,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '疯狂元素城',
    'describe': '讲述一位家庭妇女，为了参加新中国的建设，主动要学习驾驶推土机一系列故事',
    'movieImage': $r('app.media.ic_movie_seven'),
    'cardImage': '/common/ic_movie_seven.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。',
    'weburl':'https://www.maoyan.com/films/1469637'
  },
  {
    'sort': 7,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '变形金刚：超能勇士崛起',
    'describe': '讲述了大理地区，一对男女青年之间，产生了阴差阳错误会的爱情故事',
    'movieImage': $r('app.media.ic_movie_eight'),
    'cardImage': '/common/ic_movie_eight.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。',
    'weburl':'https://www.maoyan.com/films/1433776'
  },
  {
    'sort': 8,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '扫毒3：人在天涯',
    'describe': '讲述了解放战争期间，女扮男装高山参加解放军，成为副排长，与排长共同战斗的故事',
    'movieImage': $r('app.media.ic_movie_eight'),
    'cardImage': '/common/ic_movie_eight.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。',
    'weburl':'https://www.maoyan.com/films/1324999'
  },
  {
    'sort': 9,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '速度与激情10',
    'describe': '讲述了北京的一所小学，五年级的同学们先进帮后进的故事',
    'movieImage': $r('app.media.ic_movie_seven'),
    'cardImage': '/common/ic_movie_seven.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。',
    'weburl':'https://www.maoyan.com/films/343035'
  }
];

/**
 * Starring data
 */
export const STARRING_DATA: Resource[] = [
$r("app.media.ic_movie_one"),
$r("app.media.ic_movie_two"),
$r("app.media.ic_movie_three"),
$r("app.media.ic_movie_four"),
$r("app.media.ic_movie_five"),
$r("app.media.ic_movie_six")
];


/**
 * Stills data
 */
export const STILLS_DATA: Resource[] = [
$r("app.media.ic_movie_one"),
$r("app.media.ic_movie_seven"),
$r("app.media.ic_movie_eight"),
$r("app.media.ic_movie_three")
];
