
/**
 * Movie list Data
 */
export const MOVIE_LIST_DATA = [
  {
    'sort': 0,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_first'),
    'title': '八角笼中',
    'describe': 'Never Say Never\n剧情\n中国大陆 / 117分钟\n2023-07-06 09:00中国大陆上映',
    'movieImage': $r('app.media.ic_movie_one'),
    'cardImage': '/common/ic_movie_one.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star')],
    'rating': '9.5',
    'introduction': '年度最受期待现实佳作！根据真实事件改编，王宝强诚意打造普通人改写命运之路！电影讲述了向腾辉（王宝强 饰）倾注心血想把当地无人照料的孩子培养成才，这让生活本没有出路的孩子们看到了一丝通向未来的曙光。然而，随着往日的表演视频被爆出，这些“残忍、血腥”的画面刺激了不明真相的人们的神经。一夜之间，舆论开始发酵。向腾辉的生活、孩子们的前途都陷入到人们以善良为名编织的大网中，让 他们难以挣脱，重回泥沼，关于未来，他们的“出路”又将在哪……',
    'weburl': 'https://dianying.taobao.com/showDetail.htm?spm=a1z21.3046609.w2.4.32c0112aP3AGAT&showId=1424575&n_s=new&source=current'
  },
  {
    'sort': 1,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_second'),
    'title': '茶啊二中',
    'describe': 'Oh my school！\n动画 奇幻 喜剧\n中国大陆 / 91分钟\n2023-07-14 08:00中国大陆上映',
    'movieImage': $r('app.media.ic_movie_two'),
    'cardImage': '/common/ic_movie_two.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star')],
    'rating': '9.5',
    'introduction': '在“茶啊二中”，有最懂“我们”的中国式青春！当“学渣”王强与“暴力班主任”石妙娜意外灵魂互换，会是怎样“翻身解气”的体验？暑假解压包式强喜剧，一起回到笑得最大声的日子！',
    'weburl':'https://www.maoyan.com/films/1431907'
  },
  {
    'sort': 2,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_third'),
    'title': '我爱你！',
    'describe': 'Love Never Ends\n剧情 爱情 家庭\n中国大陆 / 117分钟\n2023-06-21 18:00中国大陆上映',
    'movieImage': $r('app.media.ic_movie_three'),
    'cardImage': '/common/ic_movie_three.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star')],
    'rating': '9.5',
    'introduction': '影帝影后绝赞演技，年度爱情片神作，带你领悟爱情真谛。你是否想过自己会如何老去？四个花甲老人，两段迟暮之恋，他们的爱善良而纯粹、浪漫又浓烈。在生命这段有限的旅程里，趁还来得及，我要对你说声“我爱你！”。',
    'weburl':'https://www.maoyan.com/films/1470379'
  },
  {
    'sort': 3,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_fourth'),
    'title': '长安三万里',
    'describe': '历史 动画\n中国大陆 / 168分钟\n2023-07-08 09:00中国大陆上映',
    'movieImage': $r('app.media.ic_movie_four'),
    'cardImage': '/common/ic_movie_four.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star')],
    'rating': '9.4',
    'introduction': '安史之乱爆发后数年，吐蕃大军攻打西南。大唐节度使高适交战不利，长安岌岌可危。困守孤城的高适向监军太监回忆起自己与李白的一生往事。',
    'weburl':'https://www.maoyan.com/films/1475137'
  },
  {
    'sort': 4,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_fifth'),
    'title': '消失的她',
    'describe': 'Lost In The Stars\n悬疑 犯罪 剧情\n中国大陆 / 122分钟\n2023-06-22 09:00中国大陆上映',
    'movieImage': $r('app.media.ic_movie_five'),
    'cardImage': '/common/ic_movie_five.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.2',
    'introduction': '金牌监制陈思诚继《误杀》系列后又一悬疑力作，朱一龙、倪妮、文咏珊、杜江俊男美女狂飙演技，剧情过山车反转停不下来！何非（朱一龙 饰）的妻子李木子（文咏珊 饰）在结婚周年旅行中离奇消失，在何非苦寻无果之时妻子再次现身，何非却坚持眼前的陌生女人并非妻子，妻子拿出了身份证明进行自证，夫妻二人似乎都有不可告人的秘密，随着金牌律师陈麦（倪妮 饰）介入到这起离奇案件中，更多的谜团慢慢浮现……究竟谁在说谎？端午佳节一起沉浸解谜。',
    'weburl':'https://www.maoyan.com/films/1452790'
  },
  {
    'sort': 5,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '蜘蛛侠：纵横宇宙',
    'describe': 'Spider-Man: Across The Spider-Verse\n动画 动作 科幻\n美国 / 140分钟\n2023-06-02 09:00中国大陆上映',
    'movieImage': $r('app.media.ic_movie_six'),
    'cardImage': '/common/ic_movie_six.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.2',
    'introduction': '奥斯卡最佳动画长片续作《蜘蛛侠：纵横宇宙》呈现了脑洞大开、潮流酷炫的视听风格。影片讲述了新生代蜘蛛侠迈尔斯携手蜘蛛格温，穿越多元宇宙踏上更宏大的冒险征程的故事。面临每个蜘蛛侠都会失去至亲的宿命，迈尔斯誓言打破命运魔咒，找到属于自己的英雄之路。而这个决定和蜘蛛侠2099所领军的蜘蛛联盟产生了极大冲突，一场以一敌百的蜘蛛侠大战即将拉响！',
    'weburl':'https://www.maoyan.com/films/1298450'
  },
  {
    'sort': 6,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '疯狂元素城',
    'describe': 'Elemental\n动画 喜剧\n美国 / 103分钟\n2023-06-16中国大陆上映',
    'movieImage': $r('app.media.ic_movie_seven'),
    'cardImage': '/common/ic_movie_seven.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.2',
    'introduction': '影片以一段挑战极限的爱情故事带观众走进元素城居民的生活。在四大元素风、火、水、土共同生活又泾渭分明的世界里，来自水元素的男生渡阿波（Wade）和来自火元素的女孩炉小焰（Ember）巧遇邂逅并暗生情愫，但面对“水火不相容”的客观事实和各大元素之间泾渭分明的悠久传统，两位主角将如何跨越隔阂，深入彼此的内心？一连串妙趣横生又感人肺腑的故事由此展开。',
    'weburl':'https://www.maoyan.com/films/1469637'
  },
  {
    'sort': 7,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '变形金刚：超能勇士崛起',
    'describe': 'Transformers:Rise of the Beasts\n动作 科幻 冒险\n美国 / 128分钟\n2023-06-09中国大陆上映',
    'movieImage': $r('app.media.ic_movie_eight'),
    'cardImage': '/common/ic_movie_eight.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.1',
    'introduction': '2023年顶级大银幕视觉盛宴来袭！时隔5年，变形金刚震撼归来！故事重返上世纪90年代，终极反派宇宙大帝从天而降，驱使以天灾为首的恐惧兽掀起地球危机。绝境之中，蛰伏许久的巨无霸终觉醒，联合汽车人变形出发！一场前所未有的史诗决战即将上演！',
    'weburl':'https://www.maoyan.com/films/1433776'
  },
  {
    'sort': 8,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '扫毒3：人在天涯',
    'describe': 'The White Storm 3：Heaven or Hell\n动作 犯罪 剧情\n中国大陆,中国香港 / 124分钟\n2023-07-06 18:00中国大陆上映',
    'movieImage': $r('app.media.ic_movie_nine'),
    'cardImage': '/common/ic_movie_nine.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.0',
    'introduction': '邱礼涛继《扫毒2》《拆弹专家2》后携《扫毒3：人在天涯》强势回归，古天乐郭富城刘青云三大影帝首次同台飙戏荡平金三角！毒枭康素差（刘青云 饰）和手下张建行（郭富城 饰）、欧志远（古天乐 饰）因一次意外有了过命交情，三人情同手足。康素差被香港警方通缉后带领团队逃到金三角发展，却意外发现身边藏有卧底。曾经的生死兄弟如今分崩离析，敌友难辨，何去何从……',
    'weburl':'https://www.maoyan.com/films/1324999'
  },
  {
    'sort': 9,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '速度与激情10',
    'describe': 'Fast X\n动作\n美国 / 141分钟\n2023-05-17中国大陆上映',
    'movieImage': $r('app.media.ic_movie_ten'),
    'cardImage': '/common/ic_movie_ten.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '8.8',
    'introduction': '当家人们陷入危机，唐老大（范·迪塞尔 饰）为救飞车家族再度出山。终途启程，这场前所未有的疾速狂飙，你准备好了吗？',
    'weburl':'https://www.maoyan.com/films/343035'
  }
];

/**
 * Starring data
 */
export const STARRING_DATA: Resource[] = [
  $r("app.media.ic_movie_one"),
  $r("app.media.ic_movie_two"),
  $r("app.media.ic_movie_three"),
  $r("app.media.ic_movie_four"),
  $r("app.media.ic_movie_five"),
  $r("app.media.ic_movie_six")
];


/**
 * Stills data
 */
export const STILLS_DATA: Resource[] = [
  $r("app.media.ic_movie_one"),
  $r("app.media.ic_movie_seven"),
  $r("app.media.ic_movie_eight"),
  $r("app.media.ic_movie_three")
];
